version: '2.2'
services:
  gzweb-node-1.1:
    image: robolab.innopolis.university:5000/gzweb-node:latest

    restart: on-failure

    mem_limit: 1G
    ports:
      - '8000:8000'
      - '8080:8080'

    entrypoint: /start-dev.sh
    environment:
      - 'ROS_MASTER_URI=http://robo-1.1:11346'
      - 'GAZEBO_MASTER_URI=http://robo-1.1:11345'
      - 'DOMAIN=localhost'
      - 'PORT_EDITOR=8000'
    volumes:
      - ./gzweb-node/shells/ar601_description:/home/gzweb/http/client/assets/ar601_description:ro
      - ./code_editor:/home/code_editor:rw
      - ./gzweb-node/gzweb:/home/gzweb:rw
      - ./editor-user:/home/editor:rw
      - ./gzweb-node/project_x:/home/catkin_ws/src/project_x:rw
      - ./start-dev.sh:/start-dev.sh
    networks:
      - net

networks:
  net:
