version: '2.2'
services:
  gzweb-node-1.2:
    image: gzweb
    depends_on: 
      - robo-1.2

    restart: on-failure

    mem_limit: 1G
    ports:
      - '8001:8001'
      - '8081:8080'
    entrypoint: /home/robo/start.sh
    environment:
      - 'ROS_MASTER_URI=http://robo-1.2:11346'
      - 'GAZEBO_MASTER_URI=http://robo-1.2:11345'
      - 'DOMAIN=  '
      - 'PORT_EDITOR=8001'
    volumes:
      - /IRMA/gzweb-node/robo:/home/robo:ro
      - /IRMA/code_editor:/home/code_editor:ro
      - /IRMA/gzweb-node/gzweb:/home/gzweb:ro

      - /IRMA/gzweb-node/shells/yefan_description:/home/gzweb/http/client/assets/yefan_description:ro

      - editor-user-2:/home/editor
      - project_x-user-2:/home/catkin_ws/src/project_x
    networks:
      - net


  robo-1.2:
    image: robo-yefan:1.1

    entrypoint: /home/robo/start.sh

    environment:
      - 'ROS_MASTER_URI=http://localhost:11346'
      - 'GAZEBO_MASTER_URI=http://localhost:11345'

    volumes:
      - /IRMA/gzweb-node/ros-robo/yefan:/home/robo:ro


    mem_limit: 4G

    networks:
      - net

networks:
  net:      

